AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CloudFront Website

Resources:
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BuildSource
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource:
              'Fn::Join':
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: S3BuildSource
                  - /*
            Principal: '*'
            Sid: PublicReadGetObject

  S3BuildSource:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub:
          - '${Prefix}-source-build'
          - Prefix:
              !Join [ "-", [ !Select [ "0", !Split [ "-", !Ref "AWS::StackName" ] ], !Select [ "1", !Split [ "-", !Ref "AWS::StackName" ] ] ] ]
      AccessControl: PublicRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html

  CloudFrontOriginIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Join [ '-', [ !Ref S3BuildSource, 'origin-identity' ] ]

  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: !Join [ '-', [ 'S3', !Ref S3BuildSource ] ]
            DomainName: !Join [ '.', [ !Ref S3BuildSource, 's3.amazonaws.com' ] ]
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCachingMinTTL: 10
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: !Join [ '-', [ 'S3', !Ref S3BuildSource ] ]
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        HttpVersion: http1.1
        Comment: Create by CloudFormation


